![](images/la.jpg)

### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [11]:
arr = np.array([[1, 3, 5],
                [7, 9, 11],
                [13, 15, 17]])
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [17]:
arr2 = np.array([[[1, 2], [2, 3], [4, 5]], [[1, 2], [2, 3], [4, 5]]])
arr2

array([[[1, 2],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [2, 3],
        [4, 5]]])

In [16]:
arr2.ndim

3

In [6]:
lst = [1, 3, 5]
type(lst)

list

In [9]:
# create an integer array
a = np.array([1, 4, 6, 8], dtype= 'int32')
a

array([1, 4, 6, 8])

In [10]:
# create a float array
b = np.array([0.6, 0.9, 1.9])
b

array([0.6, 0.9, 1.9])

In [12]:
# Get Dimension
arr.ndim

2

In [18]:
# Get Shape
arr.shape

(3, 3)

In [19]:
arr2.shape

(2, 3, 2)

In [20]:
# Get Type
type(arr)

numpy.ndarray

In [23]:
# Get total size
arr.nbytes

36

In [24]:
# Get number of elements
arr.size

9

In [25]:
arr2.size

12

### Accessing/Changing specific elements, rows, columns, etc

In [26]:
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [29]:
lst = [[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]]
lst

[[1, 3, 5], [7, 9, 11], [13, 15, 17]]

In [35]:
# Get a specific element [row, column]
arr[1, 1] 
# arr[1][1]

9

In [33]:
# lst[1, 1]
lst[1][1]

9

In [41]:
# Get a specific row     [start:stop:step]
arr[2, :]

array([13, 15, 17])

In [40]:
# Get a specific column
arr[:, 2]

array([ 5, 11, 17])

In [48]:
# Getting a little more fancy [startindex:endindex:stepsize]
arr3 = np.array([0,1,2,3,4,5,6,7,8,9])

arr3[1:-1:2]
arr3[4:]

array([4, 5, 6, 7, 8, 9])

In [50]:
# Replace an element
arr[1] = np.array([2,3,4])
arr

array([[ 1,  3,  5],
       [ 2,  3,  4],
       [13, 15, 17]])

*3-d example

### Initializing Different Types of Arrays

In [56]:
# All 0s matrix
zeroArr = np.zeros((2,2))
zeroArr

array([[0., 0.],
       [0., 0.]])

In [58]:
# All 1s matrix
oneArr = np.ones((2,2))
oneArr

array([[1., 1.],
       [1., 1.]])

In [121]:
# Any other number
anyArr = np.full((5,6), 99)
anyArr

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [125]:
# Any other number (full_like)
Arr = np.full_like(anyArr, 30)
Arr

array([[30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30]])

In [64]:
# Random decimal numbers
ran = np.random.rand(2,3)
ran

array([[0.6160475 , 0.95702155, 0.16192005],
       [0.18398521, 0.01262976, 0.59401884]])

In [67]:
# Random Integer values
ranint = np.random.randint(0, 100, size=(3, 3))
ranint

array([[27, 57, 98],
       [84, 32, 44],
       [80, 14, 11]])

In [70]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Be careful when copying arrays!!!

In [80]:
# Copy an Array

arr0 = np.array([[1,2], [3,4]])

lst = [1,2,[3,4]]

# Aliasing
lst2 = lst

# copy 1
lst3 = lst.copy()
# copy 2
import copy
lst4 = copy.copy(lst)
# copy 3
lst5 = lst[:]

## Deep Copy 
# import copy
lst6 = copy.deepcopy(lst)


lst.append(5)
lst[0] = 0
lst[2][0] = 10


print(lst2, lst3, lst4, lst5, lst6, sep='\n')

# a = 4
# b = a
# a = 5
# print(b)

[0, 2, [10, 4], 5]
[1, 2, [10, 4]]
[1, 2, [10, 4]]
[1, 2, [10, 4]]
[1, 2, [3, 4]]


### Mathematics

In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# array to array addition

In [83]:
a + 2

array([3, 4, 5, 6])

In [84]:
a - 2

array([-1,  0,  1,  2])

In [85]:
a * 2

array([2, 4, 6, 8])

In [86]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [88]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [87]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [89]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst1+lst2

[1, 2, 3, 4, 5, 6]

In [90]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [91]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [92]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [93]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [94]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

##### Linear Algebra

In [95]:
a = np.ones((2,3))   # n x m
print(a)

b = np.full((3,2), 2) # m x o
print(b)

np.matmul(a,b)    # n x o

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [97]:
# Find the determinant
c = np.identity(3)
np.linalg.det(np.matmul(a,b))

0.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [98]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.min(stats)

1

In [100]:
np.max(stats, axis=1)

array([3, 6])

In [101]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [107]:
# Reshape
ar = np.random.randint(0, 10, size=(3, 4))
ar

array([[6, 4, 7, 6],
       [4, 4, 6, 8],
       [9, 7, 6, 2]])

In [108]:
ar.reshape(4, 3)

array([[6, 4, 7],
       [6, 4, 4],
       [6, 8, 9],
       [7, 6, 2]])

In [111]:
# Vertically stacking vectors
varr = np.array([1,2,3])
varr2 = np.array([4,5,6])

np.vstack((varr, varr2, varr))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [112]:
# Horizontal  stack
np.hstack((varr,varr2))

array([1, 2, 3, 4, 5, 6])

### Miscellaneous
##### Load Data from File

In [116]:
filedata = np.genfromtxt('data.txt', delimiter=' ')
filedata = filedata.astype('int32')
print(filedata)

[[1 2 3]
 [4 5 6]]


##### Boolean Masking and Advanced Indexing

In [118]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False],
       [False, False, False]])